WINDOW_WIDTH = 500
WINDOW_HEIGHT = 250
BACKGROUND_COLOR = (82, 209, 116)
BLACK = (0, 0, 0)

ROWS_NUM = 25
COLS_NUM = 50


CELL_WIDTH = WINDOW_WIDTH // COLS_NUM
CELL_HEIGHT = WINDOW_HEIGHT // ROWS_NUM

EMPTY_CELL = ' '
FLAG_CELL = 'F'
MINE_CELL = 'M'


SOLDIER_IMAGE = 'soldier.png'
FLAG_IMAGE = 'flag.png'
MINE_IMAGE = 'mine.png'
GRASS_IMAGE = 'grass.png'


SOLDIER_WIDTH_CELLS = 2
SOLDIER_HEIGHT_CELLS = 4

SOLDIER_BODY_ROWS = 3
SOLDIER_LEGS_ROWS = SOLDIER_HEIGHT_CELLS - SOLDIER_BODY_ROWS  # 1

SOLDIER_START_LOCATION = (0, 0)


FLAG_WIDTH_CELLS = 4
FLAG_HEIGHT_CELLS = 3

MINE_WIDTH_CELLS = 3
MINE_HEIGHT_CELLS = 1
MINES_NUM = 20

GRASS_NUM = 20

LANDSMINES_EXPOSE_DURATION = 1
MINES_BACKGROUND_COLOR = BLACK
GRID_COLOR = (0, 120, 0)


FONT_NAME = "Calibri"

START_MESSAGE = 'WELCOME TO THE FLAG GAME.\nHAVE FUN!'
START_MESSAGE_COLOR = (255, 255, 255)
START_FONT_SIZE = 16
START_MESSAGE_LOCATION = (SOLDIER_WIDTH_CELLS * CELL_WIDTH + 5, 5)

LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = BLACK
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))

WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))

END_MESSAGE_DURATION = 3
